[build]
  command = "npm --prefix client run build"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/mealdb"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
